name: TabNet_env
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - netcdf4
  - pandas
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - cartopy
  - geopandas
  - pip:
      - h5pyd
      - NREL-rex
  - 