name: TabNet_env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - xarray
  - dask
  - netcdf4
  - pandas
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - cartopy
  - seaborn
  - geopandas
  - pytorch-tabnet
  - lightning